// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/bizjs/kratoscarf/auth/session"
	"github.com/bizjs/kratoscarf/examples/app/router-validation-demo/internal/biz"
	"github.com/bizjs/kratoscarf/examples/app/router-validation-demo/internal/conf"
	"github.com/bizjs/kratoscarf/examples/app/router-validation-demo/internal/data"
	"github.com/bizjs/kratoscarf/examples/app/router-validation-demo/internal/server"
	"github.com/bizjs/kratoscarf/examples/app/router-validation-demo/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

func wireApp(bc *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	sessMgr := session.NewManager(session.NewMemoryStore(), session.Config{
		CookieName: "todo_sid",
		CookiePath: "/",
	})
	todoRepo := data.NewTodoRepo()
	todoBiz := biz.NewTodoBiz(todoRepo)
	todoSvc := service.NewTodoService(todoBiz, sessMgr)
	httpServer := server.NewHTTPServer(&bc.Server, todoSvc)
	app := newApp(logger, httpServer)
	return app, func() {}, nil
}
