// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/bizjs/kratoscarf/examples/app/auth-app/internal/biz"
	"github.com/bizjs/kratoscarf/examples/app/auth-app/internal/conf"
	"github.com/bizjs/kratoscarf/examples/app/auth-app/internal/data"
	"github.com/bizjs/kratoscarf/examples/app/auth-app/internal/server"
	"github.com/bizjs/kratoscarf/examples/app/auth-app/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

func wireApp(bc *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	serverConfig := provideServerConfig(bc)
	jwtAuth := provideJWTAuthenticator(bc)
	sessMgr := provideSessionManager(bc)
	userRepo := data.NewUserRepo()
	userUC := biz.NewUserUsecase(userRepo)
	authSvc := service.NewAuthService(userUC, jwtAuth, sessMgr)
	httpServer := server.NewHTTPServer(serverConfig, authSvc, logger)
	app := newApp(logger, httpServer)
	return app, func() {}, nil
}
