// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/auth/v1/auth.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_JWTLogin_FullMethodName       = "/api.auth.v1.AuthService/JWTLogin"
	AuthService_JWTRefresh_FullMethodName     = "/api.auth.v1.AuthService/JWTRefresh"
	AuthService_JWTProfile_FullMethodName     = "/api.auth.v1.AuthService/JWTProfile"
	AuthService_SessionLogin_FullMethodName   = "/api.auth.v1.AuthService/SessionLogin"
	AuthService_SessionLogout_FullMethodName  = "/api.auth.v1.AuthService/SessionLogout"
	AuthService_SessionProfile_FullMethodName = "/api.auth.v1.AuthService/SessionProfile"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthService defines the auth API.
type AuthServiceClient interface {
	// JWT login — returns access + refresh token pair.
	JWTLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*TokenPair, error)
	// JWT refresh — exchange refresh token for new pair.
	JWTRefresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*TokenPair, error)
	// JWT profile — protected, requires Bearer token.
	JWTProfile(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ProfileReply, error)
	// Session login — creates server-side session, sets cookie.
	SessionLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*ProfileReply, error)
	// Session logout — destroys session.
	SessionLogout(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*MessageReply, error)
	// Session profile — protected, requires session cookie.
	SessionProfile(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ProfileReply, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) JWTLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*TokenPair, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenPair)
	err := c.cc.Invoke(ctx, AuthService_JWTLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) JWTRefresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*TokenPair, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenPair)
	err := c.cc.Invoke(ctx, AuthService_JWTRefresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) JWTProfile(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ProfileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileReply)
	err := c.cc.Invoke(ctx, AuthService_JWTProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SessionLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*ProfileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileReply)
	err := c.cc.Invoke(ctx, AuthService_SessionLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SessionLogout(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*MessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageReply)
	err := c.cc.Invoke(ctx, AuthService_SessionLogout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SessionProfile(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ProfileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileReply)
	err := c.cc.Invoke(ctx, AuthService_SessionProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// AuthService defines the auth API.
type AuthServiceServer interface {
	// JWT login — returns access + refresh token pair.
	JWTLogin(context.Context, *LoginRequest) (*TokenPair, error)
	// JWT refresh — exchange refresh token for new pair.
	JWTRefresh(context.Context, *RefreshRequest) (*TokenPair, error)
	// JWT profile — protected, requires Bearer token.
	JWTProfile(context.Context, *EmptyRequest) (*ProfileReply, error)
	// Session login — creates server-side session, sets cookie.
	SessionLogin(context.Context, *LoginRequest) (*ProfileReply, error)
	// Session logout — destroys session.
	SessionLogout(context.Context, *EmptyRequest) (*MessageReply, error)
	// Session profile — protected, requires session cookie.
	SessionProfile(context.Context, *EmptyRequest) (*ProfileReply, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) JWTLogin(context.Context, *LoginRequest) (*TokenPair, error) {
	return nil, status.Error(codes.Unimplemented, "method JWTLogin not implemented")
}
func (UnimplementedAuthServiceServer) JWTRefresh(context.Context, *RefreshRequest) (*TokenPair, error) {
	return nil, status.Error(codes.Unimplemented, "method JWTRefresh not implemented")
}
func (UnimplementedAuthServiceServer) JWTProfile(context.Context, *EmptyRequest) (*ProfileReply, error) {
	return nil, status.Error(codes.Unimplemented, "method JWTProfile not implemented")
}
func (UnimplementedAuthServiceServer) SessionLogin(context.Context, *LoginRequest) (*ProfileReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SessionLogin not implemented")
}
func (UnimplementedAuthServiceServer) SessionLogout(context.Context, *EmptyRequest) (*MessageReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SessionLogout not implemented")
}
func (UnimplementedAuthServiceServer) SessionProfile(context.Context, *EmptyRequest) (*ProfileReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SessionProfile not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_JWTLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).JWTLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_JWTLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).JWTLogin(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_JWTRefresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).JWTRefresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_JWTRefresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).JWTRefresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_JWTProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).JWTProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_JWTProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).JWTProfile(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SessionLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SessionLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SessionLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SessionLogin(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SessionLogout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SessionLogout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SessionLogout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SessionLogout(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SessionProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SessionProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SessionProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SessionProfile(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.auth.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JWTLogin",
			Handler:    _AuthService_JWTLogin_Handler,
		},
		{
			MethodName: "JWTRefresh",
			Handler:    _AuthService_JWTRefresh_Handler,
		},
		{
			MethodName: "JWTProfile",
			Handler:    _AuthService_JWTProfile_Handler,
		},
		{
			MethodName: "SessionLogin",
			Handler:    _AuthService_SessionLogin_Handler,
		},
		{
			MethodName: "SessionLogout",
			Handler:    _AuthService_SessionLogout_Handler,
		},
		{
			MethodName: "SessionProfile",
			Handler:    _AuthService_SessionProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/auth/v1/auth.proto",
}
