// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.4
// source: api/auth/v1/auth.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAuthServiceJWTLogin = "/api.auth.v1.AuthService/JWTLogin"
const OperationAuthServiceJWTProfile = "/api.auth.v1.AuthService/JWTProfile"
const OperationAuthServiceJWTRefresh = "/api.auth.v1.AuthService/JWTRefresh"
const OperationAuthServiceSessionLogin = "/api.auth.v1.AuthService/SessionLogin"
const OperationAuthServiceSessionLogout = "/api.auth.v1.AuthService/SessionLogout"
const OperationAuthServiceSessionProfile = "/api.auth.v1.AuthService/SessionProfile"

type AuthServiceHTTPServer interface {
	// JWTLogin JWT login — returns access + refresh token pair.
	JWTLogin(context.Context, *LoginRequest) (*TokenPair, error)
	// JWTProfile JWT profile — protected, requires Bearer token.
	JWTProfile(context.Context, *EmptyRequest) (*ProfileReply, error)
	// JWTRefresh JWT refresh — exchange refresh token for new pair.
	JWTRefresh(context.Context, *RefreshRequest) (*TokenPair, error)
	// SessionLogin Session login — creates server-side session, sets cookie.
	SessionLogin(context.Context, *LoginRequest) (*ProfileReply, error)
	// SessionLogout Session logout — destroys session.
	SessionLogout(context.Context, *EmptyRequest) (*MessageReply, error)
	// SessionProfile Session profile — protected, requires session cookie.
	SessionProfile(context.Context, *EmptyRequest) (*ProfileReply, error)
}

func RegisterAuthServiceHTTPServer(s *http.Server, srv AuthServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/jwt/login", _AuthService_JWTLogin0_HTTP_Handler(srv))
	r.POST("/jwt/refresh", _AuthService_JWTRefresh0_HTTP_Handler(srv))
	r.GET("/jwt/profile", _AuthService_JWTProfile0_HTTP_Handler(srv))
	r.POST("/session/login", _AuthService_SessionLogin0_HTTP_Handler(srv))
	r.POST("/session/logout", _AuthService_SessionLogout0_HTTP_Handler(srv))
	r.GET("/session/profile", _AuthService_SessionProfile0_HTTP_Handler(srv))
}

func _AuthService_JWTLogin0_HTTP_Handler(srv AuthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthServiceJWTLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.JWTLogin(ctx, req.(*LoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TokenPair)
		return ctx.Result(200, reply)
	}
}

func _AuthService_JWTRefresh0_HTTP_Handler(srv AuthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RefreshRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthServiceJWTRefresh)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.JWTRefresh(ctx, req.(*RefreshRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TokenPair)
		return ctx.Result(200, reply)
	}
}

func _AuthService_JWTProfile0_HTTP_Handler(srv AuthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EmptyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthServiceJWTProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.JWTProfile(ctx, req.(*EmptyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProfileReply)
		return ctx.Result(200, reply)
	}
}

func _AuthService_SessionLogin0_HTTP_Handler(srv AuthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthServiceSessionLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SessionLogin(ctx, req.(*LoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProfileReply)
		return ctx.Result(200, reply)
	}
}

func _AuthService_SessionLogout0_HTTP_Handler(srv AuthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EmptyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthServiceSessionLogout)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SessionLogout(ctx, req.(*EmptyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MessageReply)
		return ctx.Result(200, reply)
	}
}

func _AuthService_SessionProfile0_HTTP_Handler(srv AuthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EmptyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthServiceSessionProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SessionProfile(ctx, req.(*EmptyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProfileReply)
		return ctx.Result(200, reply)
	}
}

type AuthServiceHTTPClient interface {
	// JWTLogin JWT login — returns access + refresh token pair.
	JWTLogin(ctx context.Context, req *LoginRequest, opts ...http.CallOption) (rsp *TokenPair, err error)
	// JWTProfile JWT profile — protected, requires Bearer token.
	JWTProfile(ctx context.Context, req *EmptyRequest, opts ...http.CallOption) (rsp *ProfileReply, err error)
	// JWTRefresh JWT refresh — exchange refresh token for new pair.
	JWTRefresh(ctx context.Context, req *RefreshRequest, opts ...http.CallOption) (rsp *TokenPair, err error)
	// SessionLogin Session login — creates server-side session, sets cookie.
	SessionLogin(ctx context.Context, req *LoginRequest, opts ...http.CallOption) (rsp *ProfileReply, err error)
	// SessionLogout Session logout — destroys session.
	SessionLogout(ctx context.Context, req *EmptyRequest, opts ...http.CallOption) (rsp *MessageReply, err error)
	// SessionProfile Session profile — protected, requires session cookie.
	SessionProfile(ctx context.Context, req *EmptyRequest, opts ...http.CallOption) (rsp *ProfileReply, err error)
}

type AuthServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAuthServiceHTTPClient(client *http.Client) AuthServiceHTTPClient {
	return &AuthServiceHTTPClientImpl{client}
}

// JWTLogin JWT login — returns access + refresh token pair.
func (c *AuthServiceHTTPClientImpl) JWTLogin(ctx context.Context, in *LoginRequest, opts ...http.CallOption) (*TokenPair, error) {
	var out TokenPair
	pattern := "/jwt/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuthServiceJWTLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// JWTProfile JWT profile — protected, requires Bearer token.
func (c *AuthServiceHTTPClientImpl) JWTProfile(ctx context.Context, in *EmptyRequest, opts ...http.CallOption) (*ProfileReply, error) {
	var out ProfileReply
	pattern := "/jwt/profile"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAuthServiceJWTProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// JWTRefresh JWT refresh — exchange refresh token for new pair.
func (c *AuthServiceHTTPClientImpl) JWTRefresh(ctx context.Context, in *RefreshRequest, opts ...http.CallOption) (*TokenPair, error) {
	var out TokenPair
	pattern := "/jwt/refresh"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuthServiceJWTRefresh))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SessionLogin Session login — creates server-side session, sets cookie.
func (c *AuthServiceHTTPClientImpl) SessionLogin(ctx context.Context, in *LoginRequest, opts ...http.CallOption) (*ProfileReply, error) {
	var out ProfileReply
	pattern := "/session/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuthServiceSessionLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SessionLogout Session logout — destroys session.
func (c *AuthServiceHTTPClientImpl) SessionLogout(ctx context.Context, in *EmptyRequest, opts ...http.CallOption) (*MessageReply, error) {
	var out MessageReply
	pattern := "/session/logout"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuthServiceSessionLogout))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SessionProfile Session profile — protected, requires session cookie.
func (c *AuthServiceHTTPClientImpl) SessionProfile(ctx context.Context, in *EmptyRequest, opts ...http.CallOption) (*ProfileReply, error) {
	var out ProfileReply
	pattern := "/session/profile"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAuthServiceSessionProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
